export default {

    tabBarItem: {
            home_Normal: () => { return require('./TabBar/home_Normal.png') },
            home_Selected: () => { return require('./TabBar/home_Selected.png') },
            category_Normal: () => { return require('./TabBar/category_Normal.png') },
            category_Selected: () => { return require('./TabBar/category_Selected.png') },
            saleSell_Normal: () => { return require('./TabBar/saleSell_Normal.png') },
            saleSell_Selected: () => { return require('./TabBar/saleSell_Selected.png') },
            car_Normal: () => { return require('./TabBar/car_Normal.png') },
            car_Selected: () => { return require('./TabBar/car_Selected.png') },
            me_Normal: () => { return require('./TabBar/me_Normal.png') },
            me_Selected: () => { return require('./TabBar/me_Selected.png') },
    },


    homeItem:{
        home_Scan: () => { return require('./Home/scan_icon.png') },
        home_Search: () => { return require('./Home/search.png') },
        home_News: () => { return require('./Home/news.png') },
    },


   data: {
        "data_list":[
          {
            "name":"生活到家",
            "pic":require("./Home/findhome_9.png"),
          },
          {
            "name":"体育健身",
            "pic":require("./Home/findhome_6.png"),
          },
          {
            "name":"机票旅游",
            "pic":require("./Home/findhome_3.png"),
          },
          {
            "name":"酒店餐饮",
            "pic":require("./Home/findhome_2.png"),
          },
          {
            "name":"看病购药",
            "pic":require("./Home/findhome_1.png"),
          },
          {
            "name":"度假休闲",
            "pic":require("./Home/findhome_7.png"),
          },
          {
            "name":"社区酒吧",
            "pic":require("./Home/findhome_0.png"),
          },
          {
            "name":"娱乐唱k",
            "pic":require("./Home/findhome_10.png"),
          },
          
        ]
      },


    hot_list:{
        "lists":[
            {
                "productList":[
                    {
                        "discountEndTime":"0",
                        "discountPrice":"799",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"119215",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"TCL L32F3301B 32英寸极窄边框卧室液晶电视",
                        "pic":"http://static.cjwsc.com//image/53/f5/2b/53f52b7e0d7ef568487fb25a904a2394.jpg",
                        "previewShowTime":null,
                        "price":"799",
                        "price_on_tag":"999",
                        "sale":"6411",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"274",
                        "height": 345
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"1299",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"152484",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"威力洗衣机8KG XQB80-1699J",
                        "pic":"http://static.cjwsc.com//image/1e/e8/00/1ee800cf65dc700d29e9cbfc231c1a5e.jpg",
                        "previewShowTime":null,
                        "price":"1299",
                        "price_on_tag":"1599",
                        "sale":"817",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"37",
                        "height": 345
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"2299",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"149580",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"TCL BCD-515WEFA1 对开门电冰箱/双开门风冷无霜冰箱节能家用薄款",
                        "pic":"http://static.cjwsc.com//image/33/cd/bb/33cdbb3c94833a251d455d4cb68a6510.jpg",
                        "previewShowTime":null,
                        "price":"2299",
                        "price_on_tag":"2999",
                        "sale":"712",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"48",
                        "height": 345
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"979",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"117673",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"Ronshen/容声 BD/BC-205MB 单温顶开门卧式冰柜家用冷柜冷冻冷藏",
                        "pic":"http://static.cjwsc.com//image/43/d4/8a/43d48ace153f1cd4a52f391afb9ae54a.jpg",
                        "previewShowTime":null,
                        "price":"979",
                        "price_on_tag":"1198",
                        "sale":"639",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"134",
                        "height": 345
                    }
                ],
                "tabName":"大家电"
            },
            {
                "productList":[
                    {
                        "discountEndTime":"0",
                        "discountPrice":"53",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"108648",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"Rainbow/彩虹电热水袋防爆暖手器320/DR40-1",
                        "pic":"http://static.cjwsc.com//image/72/ea/7c/72ea7cdbe8b114e2f8240caa323e0545.jpg",
                        "previewShowTime":null,
                        "price":"53",
                        "price_on_tag":"69",
                        "sale":"883",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"221",
                        "height": 345,
                        "title":"Rainbow/彩虹电热水袋防爆暖手器320/DR40-1"

                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"169",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"152040",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"先锋小太阳暖风机DF062/NSB-8DQ5",
                        "pic":"http://static.cjwsc.com//image/44/0b/c2/440bc26a63904d64af58f6fb3d917973.jpg",
                        "previewShowTime":null,
                        "price":"169",
                        "price_on_tag":"198",
                        "sale":"661",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"150",
                        "height": 345,
                        "title":"先锋小太阳暖风机DF062/NSB-8DQ5",
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"2780",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"152371",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"供应妙能暖风桌桌暖风茶几办公桌学习餐桌空调桌",
                        "pic":"http://static.cjwsc.com//image/a8/ca/de/a8cade3ec4ab500dfdc14591c017b59a.jpg",
                        "previewShowTime":null,
                        "price":"2780",
                        "price_on_tag":"3280",
                        "sale":"884",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"1799",
                        "height": 345,
                        "title":"供应妙能暖风桌桌暖风茶几办公桌学习餐桌空调桌",
                    }
                ],
                "tabName":"生活电器"
            },
            {
                "productList":[
                    {
                        "discountEndTime":"0",
                        "discountPrice":"589",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"142857",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"签收前请检查包装是否破损，如有破损，请立即拍照并联系客服人员。GZLD陶瓷双孔虹吸式冲水 坐便器 高效静音水件 缓冲盖板设计 陶瓷马桶",
                        "pic":"http://image.cjwsc.com/goods/36/1150300144636/1150300144636001/240_240/200_2001_20170002.jpg",
                        "previewShowTime":null,
                        "price":"589",
                        "price_on_tag":"1600",
                        "sale":"449",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"9",
                        "height": 240
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"1369",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"143096",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"签收前请检查包装是否破损，如有破损，请立即拍照并联系客服人员。GZLD现代浴室柜实木卫浴柜挂式洗脸盆洗手盆组合卫生间抽屉褚物柜简约浴室柜",
                        "pic":"http://image.cjwsc.com/goods/08/1150300144908/1150300144908001/240_240/200_2001_20170004.jpg",
                        "previewShowTime":null,
                        "price":"1369",
                        "price_on_tag":"2105",
                        "sale":"639",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"12",
                        "height": 240
                    }
                ],
                "tabName":"家具建材"
            },
            {
                "productList":[
                    {
                        "discountEndTime":"0",
                        "discountPrice":"89",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"458786",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"拖把桶旋转免手洗家用自动甩干百家好世拖把桶旋转免手洗家用自动甩干拖地墩布脱水地拖布好神拖干湿两用",
                        "pic":"http://image.cjwsc.com/goods/70/1050200168070/1050200168070001/240_240/200_2001_20180001.jpg",
                        "previewShowTime":null,
                        "price":"89",
                        "price_on_tag":"199",
                        "sale":"758",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"1431",
                        "height": 240
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"19.9",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"464390",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"邦达小鸟玻璃杯360ml送杯套 超便携个性杯子DBLA25",
                        "pic":"http://image.cjwsc.com/goods/00/1050700175900/1050700175900001/240_240/200_2001_20180001.jpg",
                        "previewShowTime":null,
                        "price":"19.9",
                        "price_on_tag":"29",
                        "sale":"565",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"2106",
                        "height": 240
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"69",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"454483",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"德铂（Debo）德国特维尔 套刀不锈钢套装刀具3件套DEP-216 菜刀 多功能刀 剪刀",
                        "pic":"http://image.cjwsc.com/goods/67/1050600162167/1050600162167001/240_240/200_2001_20180001.jpg",
                        "previewShowTime":null,
                        "price":"69",
                        "price_on_tag":"199",
                        "sale":"731",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"494",
                        "height": 240
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"99",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"462059",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"美厨（maxcook）304不锈钢碗 汤碗双层隔热 餐具面碗13CM（6只装）MCWA612",
                        "pic":"http://image.cjwsc.com/goods/31/1050800173231/1050800173231001/240_240/200_2001_20180001.jpg",
                        "previewShowTime":null,
                        "price":"99",
                        "price_on_tag":"159",
                        "sale":"426",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"97",
                        "height": 240
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"99",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"84292",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"美日盈 MG3009 2.0L 304不锈钢真空欧式保温壶 保温瓶",
                        "pic":"http://image.cjwsc.com/goods/87/201300075587/84292020223015651/240_240/200_2001_20160001.jpg",
                        "previewShowTime":null,
                        "price":"99",
                        "price_on_tag":"298",
                        "sale":"581",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"196",
                        "height": 240
                    }
                ],
                "tabName":"日用家居"
            },
            {
                "productList":[
                    {
                        "discountEndTime":"0",
                        "discountPrice":"98",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"465994",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"凯美妮家纺 YG网红大阪双层数码印花卡通羊羔绒毯子多尺寸可选",
                        "pic":"http://image.cjwsc.com/goods/15/1050100178615/1050100178615001/240_240/200_2001_20180001.jpg",
                        "previewShowTime":null,
                        "price":"98",
                        "price_on_tag":"688",
                        "sale":"584",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"4200", 
                        "height": 240
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"115",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"455244",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"可慕家纺 儿童乳胶枕 泰国进口天然乳胶W",
                        "pic":"http://image.cjwsc.com/goods/45/1050100163245/1050100163245001/240_240/200_2001_20180002.jpg",
                        "previewShowTime":null,
                        "price":"115",
                        "price_on_tag":"169",
                        "sale":"630",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"498",
                        "height": 240
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"175",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"464208",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"可慕家纺 高密全棉活性印花纯棉12868四件套L",
                        "pic":"http://image.cjwsc.com/goods/17/1050100176217/1050100176217001/240_240/200_2001_20180001.jpg",
                        "previewShowTime":null,
                        "price":"175",
                        "price_on_tag":"398",
                        "sale":"605",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"595",
                        "height": 240
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"246",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"454847",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"VIPLIFE家纺 精梳全棉四件套床单被套清新田园风-海棠花语-100027",
                        "pic":"http://image.cjwsc.com/goods/75/1050100162675/1050100162675001/240_240/200_2001_20180001.jpg",
                        "previewShowTime":null,
                        "price":"246",
                        "price_on_tag":"615",
                        "sale":"690",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"98",
                        "height": 240
                    }
                ],
                "tabName":"精品家纺"
            },
            {
                "productList":[
                    {
                        "discountEndTime":"0",
                        "discountPrice":"179",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"147140",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"苏盈珈可韩版潮时尚秋季休闲卫衣两件套S68263",
                        "pic":"http://image.cjwsc.com/goods/14/1060100147814/1060100147814001/240_240/200_2001_20170002.jpg",
                        "previewShowTime":null,
                        "price":"179",
                        "price_on_tag":"899",
                        "sale":"453",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"999",
                        "height": 240
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"89",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"465464",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"【72小时发货】名鹰春秋季宽松棉质直筒商务男裤休闲裤男士裤子D983XX0001",
                        "pic":"http://image.cjwsc.com/goods/36/1060200178036/1060200178036001/240_240/200_2001_20180001.jpg",
                        "previewShowTime":null,
                        "price":"89",
                        "price_on_tag":"328",
                        "sale":"477",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"233",
                        "height": 240
                    }
                ],
                "tabName":"服饰鞋包"
            },
            {
                "productList":[
                    {
                        "discountEndTime":"0",
                        "discountPrice":"39.9",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"468248",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"贝柔绿茶原木抽纸3层90抽纸30包装抽取式面巾纸餐巾纸孕婴可用",
                        "pic":"http://image.cjwsc.com/goods/95/1070100181595/1070100181595001/240_240/200_2001_20180001.jpg",
                        "previewShowTime":null,
                        "price":"39.9",
                        "price_on_tag":"59.9",
                        "sale":"2269",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"4332",
                        "height": 240
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"100.8",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"471379",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"黑人茶倍健牙膏140g X6支促销清新口气防蛀健齿（茉莉白茶）19729",
                        "pic":"http://image.cjwsc.com/goods/92/1070100186092/1070100186092001/240_240/200_2001_20180001.jpg",
                        "previewShowTime":null,
                        "price":"100.8",
                        "price_on_tag":"179.4",
                        "sale":"513",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"9999",
                        "height": 240
                    },
                    {
                        "discountEndTime":"1561910400",
                        "discountPrice":"129",
                        "discountStartTime":"1560736800",
                        "freeFlag":false,
                        "id":"149202",
                        "isLimitStock":true,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"丹姿水密码-补水明星组合",
                        "pic":"http://image.cjwsc.com/goods/96/1070200150496/1070200150496001/240_240/200_2001_20170001.jpg",
                        "previewShowTime":"1560823200",
                        "price":"149",
                        "price_on_tag":"188",
                        "sale":"839",
                        "stockNumberLimit":"100",
                        "stockNumberLimitSale":"936",
                        "stock_num":"936",
                        "height": 240
                    },
                    {
                        "discountEndTime":"0",
                        "discountPrice":"55",
                        "discountStartTime":"0",
                        "freeFlag":false,
                        "id":"458035",
                        "isLimitStock":false,
                        "isavctive_full":false,
                        "isdouble":false,
                        "isfree":"",
                        "name":"新田村早餐麦片食品纯燕麦片即食原味混合谷物速食冲饮早餐营养小袋装400g*4",
                        "pic":"http://image.cjwsc.com/goods/92/1110100167192/1110100167192001/240_240/200_2001_20180001.jpg",
                        "previewShowTime":null,
                        "price":"55",
                        "price_on_tag":"76",
                        "sale":"569",
                        "stockNumberLimit":null,
                        "stockNumberLimitSale":null,
                        "stock_num":"2974",
                        "height": 240
                    }
                ],
                "tabName":"更多推荐"
            }
        ]
    },




}